jwt:
  public:
    key:  classpath:app.pub.key
  private:
    key: classpath:app.key

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
